---

driver:
  name: digitalocean
  size: s-2vcpu-4gb
  private_networking: false
  region: ams2
  tags: do_test_pool
  # the second firewall id is for the letsencypt inbound port 80 access
  firewalls: <%= ENV['DO_FIREWALL_ID'] %>,<%= ENV['DO_FIREWALL_ID2'] %>

transport:
  ssh_key: ~/.ssh/id_rsa.do-buildbot

platforms:
  - name: debian-9
  - name: ubuntu-16
  - name: ubuntu-18
  - name: centos-6
    extra_vars:
      certbot_timer: cron
    verifier:
      attributes:
        skiplist:
          - renew-systemd-timer-1
  - name: centos-7
  - name: fedora-28

verifier:
  name: inspec
  attributes:
    skiplist:
      - renew-cron-1
  # format: cli
  format: documentation
  # format: json-rspec
  # format: json
  # output: reports/limepepper.foreman/%{platform}_%{suite}_inspec.json
  # format: progress

suites:
  - name: default
  #   tk_dep_roles:
  #     - limepepper.mysql
  #     - limepepper.apache
  - name: dns-do
    provisioner:
      playbook: tests/dns-digitalocean.yml
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/certchecks
        # - test/integration/plugin-dns-digitalocean
  - name: dns-r53
    provisioner:
      playbook: tests/dns-route53.yml
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/certchecks
        # - tests/inspec/certbot-plugin-dns-digitalocean
  - name: webroot
    provisioner:
      playbook: tests/webroot.yml
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/certchecks
        - test/integration/timer-checks
        # - test/integration/plugin-webroot
        # - https://github.com/dev-sec/ssl-benchmark
