---

driver:
  name: digitalocean
  size: s-2vcpu-4gb
  private_networking: false
  region: lon1
  tags: do_test_pool
  # the second firewall id is for the letsencypt inbound port 80 access
  firewalls: <%= ENV['DO_FIREWALL_ID'] %>,<%= ENV['DO_FIREWALL_ID2'] %>

transport:
  ssh_key: ~/.ssh/id_rsa.do-buildbot

platforms:
  - name: debian-9
  - name: ubuntu-16
  - name: ubuntu-18
  # - name: centos-7
  - name: centos-6
  - name: centos-7
  # - name: fedora-27
  - name: fedora-28

# kitchen-inspec expects test to be in test/integration/%suite%/inspec
# verifier:
#   name: inspec
#   # format: junit
#   # output: path/to/results/%{platform}_%{suite}_inspec.xml
#   inspec_tests:
#     #- tests/inspec/default
#     - name: test-wordpress
#       path: tests/inspec/default

suites:
  - name: default
    provisioner:
      show_command_output: true
      # extra_vars:
      #   webserver_options:
      #     - mod-php
      #     - virtualhost
      #   tk_dep_roles:
      #     - limepepper.mysql
      #     - limepepper.apache
  - name: plugin-dns-digitalocean
    provisioner:
      playbook: tests/test-certbot-plugin-dns-digitalocean.yml
    verifier:
      inspec_tests:
        - tests/inspec/default
        - tests/inspec/certchecks
        - tests/inspec/certbot-plugin-dns-digitalocean
  - name: plugin-dns-route53
    provisioner:
      playbook: tests/test-certbot-plugin-dns-route53.yml
    verifier:
      inspec_tests:
        - tests/inspec/default
        - tests/inspec/certchecks
        # - tests/inspec/certbot-plugin-dns-digitalocean
  - name: plugin-webroot
    provisioner:
      playbook: tests/test-certbot-plugin-webroot.yml
    verifier:
      inspec_tests:
        - tests/inspec/default
        - tests/inspec/certchecks
        - tests/inspec/plugin-webroot
        # - https://github.com/dev-sec/ssl-benchmark
