---

driver:
  name: digitalocean
  size: s-2vcpu-4gb
  private_networking: false
  region: ams2
  tags: do_test_pool
  # the second firewall id is for the letsencypt inbound port 80 access
  firewalls: <%= ENV['DO_FIREWALL_ID'] %>,<%= ENV['DO_FIREWALL_ID2'] %>

transport:
  ssh_key: ~/.ssh/id_rsa.do-buildbot

platforms:
  - name: debian-9
  - name: ubuntu-16
  - name: ubuntu-18
  - name: centos-6
    extra_vars:
      certbot_timer: cron
    verifier:
      attributes:
        skiplist:
          - renew-systemd-timer-1
  - name: centos-7
  - name: fedora-28
