---

driver:
  name: vagrant
  network:
    - ["private_network", { type: "dhcp" }]
  cachier: ":machine"
  vagrantfiles:
    - vagrant/vagrant.rb
  vagrantfile_erb: vagrant/Vagrantfile.erb
  var_suffix: testbox

transport:
  max_ssh_sessions: 5

provisioner:
  name: ansible_push
  playbook: tests/test.yml
  chef_bootstrap_url: nil
  # ansible_config      : "/path/to/ansible/ansible.cfg"
  verbose: "<%= ENV.key?('ANSIBLE_Vs') ? ENV['ANSIBLE_Vs'] : 'vv' %>"
  tags: <%= ENV['ANSIBLE_TAGS'] %>
  skip_tags: <%= ENV['ANSIBLE_SKIP_TAGS'] %>
  extra_vars:
    ara_enabled: true

platforms:
  - name: ubuntu-17.10
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7
  - name: centos-6
  # - name: fedora-27
  - name: fedora-28
  # - name: oracle-5.11
  # - name: oracle-7.4
  # - name: oracle-6.9
  - name: debian-8
  - name: debian-9

verifier:
  name: inspec
  attributes:
    skiplist:
      - renew-cron-1
  # format: cli
  format: documentation
  # format: json-rspec
  # format: json
  # output: reports/limepepper.foreman/%{platform}_%{suite}_inspec.json
  # format: progress

suites:
  - name: default
  #   tk_dep_roles:
  #     - limepepper.mysql
  #     - limepepper.apache
  - name: dns-do
    provisioner:
      playbook: tests/dns-digitalocean.yml
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/certchecks
        # - test/integration/plugin-dns-digitalocean
  - name: dns-r53
    provisioner:
      playbook: tests/dns-route53.yml
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/certchecks
        # - tests/inspec/certbot-plugin-dns-digitalocean
  - name: webroot
    provisioner:
      playbook: tests/webroot.yml
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/certchecks
        - test/integration/timer-checks
        # - test/integration/plugin-webroot
        # - https://github.com/dev-sec/ssl-benchmark
