---

driver:
  name: vagrant
  network:
    - ["private_network", { type: "dhcp" }]
  cachier: ":machine"
  vagrantfiles:
    - vagrant/vagrant.rb
  vagrantfile_erb: vagrant/Vagrantfile.erb
  var_suffix: testbox

transport:
  max_ssh_sessions: 5

provisioner:
  name: ansible_push
  playbook: tests/test.yml
  chef_bootstrap_url: nil
  # ansible_config      : "/path/to/ansible/ansible.cfg"
  verbose: "<%= ENV.key?('ANSIBLE_Vs') ? ENV['ANSIBLE_Vs'] : 'vv' %>"
  tags: <%= ENV['ANSIBLE_TAGS'] %>
  skip_tags: <%= ENV['ANSIBLE_SKIP_TAGS'] %>
  extra_vars:
    ara_enabled: true

platforms:
  - name: ubuntu-17.10
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7
  - name: centos-6
  # - name: fedora-27
  - name: fedora-28
  # - name: oracle-5.11
  # - name: oracle-7.4
  # - name: oracle-6.9
  - name: debian-8
  - name: debian-9

# kitchen-inspec expects test to be in test/integration/%suite%/inspec
verifier:
  name: inspec
  # why are they setting inspec sude true???
  # sudo: true
  # format: junit
  # format: json
  # output: reports/limepepper.foreman/%{platform}_%{suite}_inspec.json
  # format: progress
  inspec_tests:
    - tests/inspec/default
  attributes:
    skiplist:
      - mysql-skip-this

suites:
  - name: default
    # provisioner:
    #   extra_vars:
    #     test_site: role-wordpress11
    #     enviro: dev
    #     test_suite: default
    # driver:
    #   hostmanager:
    #     alias_suffix: .testbox
    #     aliases:
    #       - role-wordpress11
