
---

services: docker

env:
  - distro: centos6
    playbook: test.yml

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.github.com/tolland/45a03a95e2db57712c1e30127c34a195/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

