---

- tags: [ letsencrypt, certbot ]
  block:

  - package:
      name:
        - python34
        - python34-setuptools

  - name: configure pip3
    shell:
      cmd: |
        cd /usr/lib/python3.4/site-packages/
        python3 easy_install.py pip
      creates: /usr/bin/pip3

  - pip:
      name: urllib3
      version: 1.23
      executable: /usr/bin/pip3

  - pip:
      name:
        - certbot
        - certbot-dns-digitalocean
        - certbot-dns-ovh
        - certbot-dns-route53
        # - certbot-vault
      executable: /usr/bin/pip3

  - name: script to list out cron jobs for all users, useful for testing
    template:
      src: cron/cron-report.sh
      dest: /var/cache/ansible/certbot/cron-report.sh
      owner: root
      group: root
      mode: 0700

  - name: create the /etc/cron.d dir
    file:
      name: /etc/cron.d
      state: directory

  - name: on centos-6, so copy in the cron job
    template:
      src: cron/Linux.j2
      dest: /etc/cron.d/certbot
      owner: root
      group: root
      mode: 0640
