---

- tags: [ letsencrypt, docert ]
  become: yes
  block:

    - when: cert.dnsprovider is not defined
      block:

        - debug:
            msg: |
              {{  lookup('dig', cert.domain, 'qtype=NS' ) }}

        # - name: add zabbix to hosts file
        #   debug:
        #     msg: "{{ cert.domain }} : {{ item }}"
        #   with_items: "{{ lookup('dig', cert.domain, 'qtype=NS', wantlist=True ) }}"

        # - debug:
        #     msg: |
        #       {{ cert.domain | parse_tld }}

        - set_fact:
            nameserver: "{{ lookup('dig', cert.domain, 'qtype=NS', wantlist=True ) | first }}"

        - set_fact:
            dnsprovider: none

        - set_fact:
            dnsprovider: digitalocean
          when: nameserver is match("ns\d+\.digitalocean\.com\.")

        - set_fact:
            dnsprovider: route53
          when: nameserver is match("ns-\d+\.awsdns-\d+.*\.")

        - debug:
            var: dnsprovider

    - when: cert.dnsprovider is defined
      block:
        - set_fact:
            dnsprovider: "{{ cert.dnsprovider }}"


    - include_tasks: "../challenges/dns-{{ dnsprovider }}.yml"
      when: "dnsprovider != 'none'"
