---

- tags: [ certbot ]
  become: yes
  block:

  # - package:
  #     name:
  #       - software-properties-common

  # # On Debian target
  # - apt_repository:
  #     repo: 'ppa:certbot/certbot'
  #     codename: trusty

  - name: install certbot using package mgr
    package:
      name: certbot
    when:
      - ansible_distribution != 'Debian'
      - ansible_distribution_major_version != '8'

  - name: install certbot using apt from jessie
    apt:
      name: certbot
      default_release: jessie-backports
    when:
      - ansible_distribution == 'Debian'
      - ansible_distribution_major_version == '8'
