---

- tags: [ certbot ]
  become: yes
  block:

  - pip:
      name: urllib3
      version: 1.23
      # executable: /usr/bin/pip3

  - pip:
      name:
        - certbot
        - certbot-dns-digitalocean
        - certbot-dns-ovh
        - certbot-dns-route53

  # There is an older version in the stretch-backports debian repo
  # but no dns plugins, which are in sid

  # - package:
  #     name:
  #       - software-properties-common

  # - apt_repository:
  #     repo: deb http://ftp.debian.org/debian stretch-backports main
  #     state: present

  # - apt:
  #     name: certbot
  #     default_release: stretch-backports

  # - apt_repository:
  #     repo: deb http://ftp.de.debian.org/debian sid main
  #     state: present

  # - apt:
  #     name:
  #       - python3-certbot-dns-route53
  #       - python3-certbot-dns-digitalocean

  - name: install certbot systemd service unit file
    template:
      src: systemd/certbot.service
      dest: /etc/systemd/system/{{ certbot_timer_servicename }}.service
    register: certbot_service_systemd_unit

  - name: install certbot systemd timer unit file
    template:
      src: systemd/certbot.timer
      dest: "/etc/systemd/system/{{ certbot_timer_servicename }}.timer"
    register: certbot_timer_systemd_unit

  - name: Make sure {{ certbot_timer_servicename }} timer is running
    systemd:
      state: started
      enabled: yes
      daemon_reload: yes
      name: "{{ certbot_timer_servicename }}.timer"
    when: certbot_service_systemd_unit.changed or certbot_timer_systemd_unit.changed
