---

- tags: [ certbot, letsencrypt ]
  block:

    - name: create the /var/cache/ansible/certbot dir
      file:
        name: /var/cache/ansible/certbot
        state: directory
        mode: 0755

    - name: debug out the version
      debug:
        msg: "ansible_distribution_version: {{ ansible_distribution_version }}"

    - name: "include distro specific tasks"
      tags: always
      include_tasks: "{{ include_install_tasks }}"
      with_first_found:
        - files:
            - "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
            - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
            - "{{ ansible_distribution }}.yml"
            - "{{ ansible_os_family }}.yml"
            - "{{ ansible_system }}.yml"
      loop_control:
        loop_var: include_install_tasks
