---

- tags: [ certbot ]
  block:

  # - package:
  #     name:
  #       - software-properties-common

  # - apt_repository:
  #     repo: 'ppa:certbot/certbot'
  #     # codename: xenial

  - package:
      name:
        - certbot
        - python-certbot-apache
        - python3-certbot-dns-digitalocean
        - python3-certbot-dns-route53
