---

- tags: [ certbot ]
  block:

  - name: install some stuff required by debian
    package:
      name:
        - software-properties-common

  - name: add the certbot ppa to Ubuntu 16.04
    apt_repository:
      repo: 'ppa:certbot/certbot'
      # codename: xenial

  - name: "certbot packages for {{ ansible_distribution }}-{{ ansible_distribution_version }}"
    package:
      name:
        - certbot
        - python-certbot-apache
        - python3-certbot-dns-digitalocean
        # - python3-certbot-dns-route53
