---

- tags: [ certbot ]
  become: yes
  block:

  - debug:
      var: bootstrap_done

    # boilerplate
  - name: bootstrap enough that ansible can run most ansible modules
    include_tasks: "bootstrap/main.yml"
    when: bootstrap_done is not defined
    tags: [ bootstrap ]

    # boilerplate
  - include_tasks: bootstrap/distro-vars-import.yml
    tags: always

    ## START OF MAIN TASKS SECTION ##

  - include_tasks: install/main.yml
    tags: always

    ## END OF MAIN TASKS SECTION ##

  # boilerplate
  # the idea here, is that if any of the tasks fail, it will add useful
  # troubleshooing tools to the build.
  rescue:
  - include_tasks: bootstrap/distro-debug-packages.yml

  - fail:
      msg: "force a failure due to previous errors"
